### ISSUE TITLE
Stripe SDK does not support provisioning profiles  using SPM

### ISSUE THREAD

**Issue by YahiaRagae** [stripe/stripe-ios#2088]
## Summary
CI/CD is failing after adding  the Stripe SDK `23.1.1`

```
 /Users/cicd/Library/Developer/Xcode/DerivedData/app/SourcePackages/checkouts/stripe-ios-spm/Package.swift: error: Stripe_StripeUICore does not support provisioning profiles. Stripe_StripeUICore does not support provisioning profiles, but provisioning profile PROVISION_PROFILE_NAME has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'Stripe_StripeUICore' from project 'Stripe')

/Users/cicd/Library/Developer/Xcode/DerivedData/app/SourcePackages/checkouts/stripe-ios-spm/Package.swift: error: Stripe_Stripe does not support provisioning profiles. Stripe_Stripe does not support provisioning profiles, but provisioning profile PROVISION_PROFILE_NAME has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'Stripe_Stripe' from project 'Stripe')

/Users/cicd/Library/Developer/Xcode/DerivedData/app/SourcePackages/checkouts/stripe-ios-spm/Package.swift: error: Stripe_Stripe3DS2 does not support provisioning profiles. Stripe_Stripe3DS2 does not support provisioning profiles, but provisioning profile PROVISION_PROFILE_NAME has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'Stripe_Stripe3DS2' from project 'Stripe')

/Users/cicd/Library/Developer/Xcode/DerivedData/app/SourcePackages/checkouts/stripe-ios-spm/Package.swift: error: Stripe_StripeCore does not support provisioning profiles. Stripe_StripeCore does not support provisioning profiles, but provisioning profile PROVISION_PROFILE_NAME has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'Stripe_StripeCore' from project 'Stripe')

/Users/cicd/Library/Developer/Xcode/DerivedData/app/SourcePackages/checkouts/stripe-ios-spm/Package.swift: error: Stripe_StripePayments does not support provisioning profiles. Stripe_StripePayments does not support provisioning profiles, but provisioning profile PROVISION_PROFILE_NAME has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target 'Stripe_StripePayments' from project 'Stripe')
```
I'm using manual signing

## Code to reproduce
N/A

## iOS version
`Xcode 14.1`

## Installation method
`SPM`

## SDK version
`23.1.1`

## Other information

Here is the `Xcode@5` task I'm using via Azure DevOps
```
- task: Xcode@5
  displayName: 'Build and Sign iPA ${{ parameters.AppBuildNumber}}-${{ parameters.SDK}}-${{ parameters.Configuration}}'
  inputs:
    xcWorkspacePath: './${{ parameters.xcWorkspaceFileName }}.xcworkspace'
    actions: 'clean'
    configuration: '${{ parameters.Configuration }}'
    sdk: '${{ parameters.SDK }}'
    scheme: '${{ parameters.scheme }}'
    packageApp: true
    archivePath: '${{ parameters.AppOutputDir }}'
    exportPath: '${{ parameters.AppOutputDir }}'
    signingOption: 'manual'
    signingIdentity: ${{ parameters.AppleCertificateSingingIdentity }}
    provisioningProfileUuid: ${{ parameters.AppleProvisionProfileUUID }}
    provisioningProfileName: ${{ parameters.AppleProvisionProfileName }}
    useXcpretty: ${{ parameters.useXcpretty }}
```
